In [18]:
import os
import pandas as pd

### AINI-Stroke AIT for 2022-2023
AIT (Accident ischemique transitoire) = Not visible on ADC ("healthy ADC")

In [ ]:
clinical_data_2022 = pd.read_csv("/bettik/PROJECTS/pr-gin5_aini/fehrdelt/datasets/donnees_cliniques/Clinical_data_2022.csv")
clinical_data_2023 = pd.read_csv("/bettik/PROJECTS/pr-gin5_aini/fehrdelt/datasets/donnees_cliniques/Clinical_data_2023.csv")

In [ ]:
correspondance_noms_2022 = pd.read_csv("/bettik/PROJECTS/pr-gin5_aini/fehrdelt/datasets/donnees_cliniques/correspondance_noms_2022.csv", names=["n°patient", "Shanoir_name"])
correspondance_noms_2023 = pd.read_csv("/bettik/PROJECTS/pr-gin5_aini/fehrdelt/datasets/donnees_cliniques/correspondance_noms_2023.csv", names=["n°patient", "Shanoir_name"])

In [ ]:
correspondance_noms_2022.head()

    n°patient       Shanoir_name
0  2022UNVG-3  aini-stroke-22001
1  2022UNVG-4  aini-stroke-22002
2  2022UNVG-5  aini-stroke-22003
3  2022UNVG-6  aini-stroke-22004
4  2022UNVG-7  aini-stroke-22005

In [ ]:
clinical_data_2022.head()

,n°patient,Age,sexe,UNV,mode_entree_CHUGA,alerte_AVC,date_admission,heure_admission,date_sortie,mode_sortie,...,type_recanalisation,date_thrombolyse,heure_thrombolyse,date_ponction,heure_ponction,date_recanalisation,heure_recanalisation,TICI_final,commentaire,fiche_validé
0,2022UNVG-18,47,H,Grenoble,via IRM directe,Oui,1/5/2022,11:35,1/8/2022,Domicile,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OUI
1,2022UNVG-22,46,F,Grenoble,via SAU,Non,1/6/2022,10:08,1/10/2022,Domicile,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OUI
2,2022UNVG-43,66,H,Grenoble,via SAU,Non,1/12/2022,17:56,1/17/2022,Domicile,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OUI
3,2022UNVG-47,77,F,Grenoble,via SAU,Non,1/14/2022,16:52,1/18/2022,Domicile,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OUI
4,2022UNVG-58,77,H,Grenoble,via SAU,Non,1/18/2022,17:25,1/22/2022,Domicile,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OUI

In [ ]:
# list all columns
clinical_data_2022["type_imagerie"]

0           IRM
1           IRM
2       Scanner
3       Scanner
4       Scanner
         ...
1058        NaN
1059    Scanner
1060        NaN
1061    Scanner
1062    Scanner
Name: type_imagerie, Length: 1063, dtype: object

In [ ]:
clinical_data_2022 = pd.merge(clinical_data_2022, correspondance_noms_2022, on="n°patient", how='left')
clinical_data_2023 = pd.merge(clinical_data_2023, correspondance_noms_2023, on="n°patient", how='left')

In [ ]:
AITs_2022 = clinical_data_2022.loc[clinical_data_2022["diagnostic"]=="AIT"]["Shanoir_name"]
AITs_2022_and_IRM = clinical_data_2022.loc[(clinical_data_2022["diagnostic"]=="AIT") & (clinical_data_2022["type_imagerie"]=="IRM")]["Shanoir_name"]

AITs_2023 = clinical_data_2023.loc[clinical_data_2023["diagnostic"]=="AIT"]["Shanoir_name"]
AITs_2023_and_IRM = clinical_data_2023.loc[(clinical_data_2023["diagnostic"]=="AIT") & (clinical_data_2023["type_imagerie"]=="IRM")]["Shanoir_name"]

In [ ]:
names_AITs = AITs_2022_and_IRM.to_list() + AITs_2023_and_IRM.to_list()
print(len(names_AITs))

32

In [ ]:
print(names_AITs)

['aini-stroke-22016', 'aini-stroke-22019', 'aini-stroke-22037', 'aini-stroke-22040', 'aini-stroke-22049', 'aini-stroke-22051', 'aini-stroke-22059', nan, 'aini-stroke-22065', 'aini-stroke-22078', 'aini-stroke-22083', 'aini-stroke-22085', 'aini-stroke-22108', 'aini-stroke-22146', 'aini-stroke-22159', nan, 'aini-stroke-22171', 'aini-stroke-22177', 'aini-stroke-22181', 'aini-stroke-22188', 'aini-stroke-22211', 'aini-stroke-22228', 'aini-stroke-22243', 'aini-stroke-22256', 'aini-stroke-22267', 'aini-stroke-22287', 'aini-stroke-22288', 'aini-stroke-22294', 'aini-stroke-22309', 'aini-stroke-22314', 'aini-stroke-22327', 'aini-stroke-22329', 'aini-stroke-22337', 'aini-stroke-22347', 'aini-stroke-22351', 'aini-stroke-22357', 'aini-stroke-22375', 'aini-stroke-22424', 'aini-stroke-22445', 'aini-stroke-22455', nan, 'aini-stroke-22497', 'aini-stroke-22501', 'aini-stroke-22506', 'aini-stroke-22523', 'aini-stroke-22529', 'aini-stroke-22550', 'aini-stroke-22552', 'aini-stroke-22559', 'aini-stroke-22561', 'aini-stroke-22563', 'aini-stroke-22600', 'aini-stroke-22611', 'aini-stroke-22617', 'aini-stroke-22649', 'aini-stroke-22654', 'aini-stroke-22666', 'aini-stroke-22684', 'aini-stroke-22692', 'aini-stroke-22747', 'aini-stroke-22758', 'aini-stroke-22787', 'aini-stroke-22796', 'aini-stroke-22822', 'aini-stroke-22862', 'aini-stroke-22872', 'aini-stroke-22879', 'aini-stroke-22880', 'aini-stroke-22883', 'aini-stroke-22909', 'aini-stroke-22928', 'aini-stroke-22937', 'aini-stroke-22948', 'aini-stroke-22981', 'aini-stroke-22982', 'aini-stroke-23011', 'aini-stroke-23013', nan, 'aini-stroke-23034', 'aini-stroke-23035', 'aini-stroke-23042', 'aini-stroke-23050', 'aini-stroke-23051', 'aini-stroke-23058', 'aini-stroke-23097', 'aini-stroke-23106', 'aini-stroke-23113', 'aini-stroke-23136', 'aini-stroke-23137', 'aini-stroke-23142', 'aini-stroke-23166', 'aini-stroke-23167', 'aini-stroke-23168', 'aini-stroke-23179', 'aini-stroke-23187', 'aini-stroke-23201', 'aini-stroke-23213', 'aini-stroke-23222', 'aini-stroke-23232', 'aini-stroke-23233', 'aini-stroke-23236', 'aini-stroke-23238', 'aini-stroke-23246', 'aini-stroke-23252', 'aini-stroke-23256', 'aini-stroke-23262', 'aini-stroke-23275', 'aini-stroke-23276', 'aini-stroke-23277', 'aini-stroke-23279', 'aini-stroke-23287', 'aini-stroke-23292', 'aini-stroke-23314', 'aini-stroke-23328', 'aini-stroke-23356', 'aini-stroke-23366', nan, 'aini-stroke-23398', 'aini-stroke-23411', 'aini-stroke-23415', 'aini-stroke-23420', nan, nan, 'aini-stroke-23434', 'aini-stroke-23458', 'aini-stroke-23465', 'aini-stroke-23494', 'aini-stroke-23514', 'aini-stroke-23572', 'aini-stroke-23576', 'aini-stroke-23592', 'aini-stroke-23608', 'aini-stroke-23621', 'aini-stroke-23660', 'aini-stroke-23671', 'aini-stroke-23677', 'aini-stroke-23683']

Pk ça commence à 2022UNVG-3
psk y'a pas date pour unvg-1 et 2 dans le csv de Zaza

### AINI-Stroke AIT for 2018-2021
AIT (Accident ischemique transitoire) = Not visible on ADC ("healthy ADC")

In [3]:
clinical_data_2018_2023 = pd.read_csv("/bettik/PROJECTS/pr-gin5_aini/fehrdelt/datasets/donnees_cliniques/AINI-Stroke_2018-2021_filtered_05-2023.csv")

In [5]:
clinical_data_2018_2023.head()

,id_data,@07_sexe,AGE,@12_d_admi_etab,@14_h_admi_etab,@16_d_sortie_ets,@33_debut_troubles,@34_d_debut_troubles,@36_h_debut_troubles,@31_mod_sortie_unv2,...,@73_h_recanalisation,@75_tici,@75_tici_av2019,@76_situation_nri_1,@76_situation_nri_2,@76_situation_nri_3,@76_situation_nri_4,@76_situation_nri_5,@76_situation_nri_autre,@76_situation_tiv_nri
0,aini-stroke-9943,1,75.0,1/1/2018,10:43,16-Jan-18,1,01-JAN-2018,09:00:00 AM,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,aini-stroke-9946,1,83.0,1/2/2018,21:14,11-Jan-18,1,02-JAN-2018,03:00:00 PM,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,aini-stroke-9947,2,63.0,1/2/2018,13:17,5-Jan-18,1,02-JAN-2018,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,aini-stroke-9981,2,91.0,1/2/2018,12:51,6-Feb-18,1,17-JAN-2018,10:00:00 AM,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,aini-stroke-9948,2,81.0,1/3/2018,22:13,10-Jan-18,1,03-JAN-2018,08:00:00 PM,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
AITs_2018_2021 = clinical_data_2018_2023.loc[clinical_data_2018_2023["@32_diag_2"]==2]["id_data"]

AITs_2018_2021_and_IRM = clinical_data_2018_2023.loc[(clinical_data_2018_2023["@32_diag_2"]==2) & (clinical_data_2018_2023["@38_imagerie"]==1)]["id_data"]

In [16]:
names_AITs = AITs_2018_2021_and_IRM.to_list()
print(len(names_AITs))

57

In [19]:
folder_to_process = "/bettik/PROJECTS/pr-gin5_aini/fehrdelt/datasets/Aini-Stroke_ADC/Others_2018_2021/"
AIT_folder_2018_2021 = "/bettik/PROJECTS/pr-gin5_aini/fehrdelt/datasets/Aini-Stroke_ADC/AIT_2018_2021/"

for file in os.listdir(folder_to_process):
    if file.split('_')[0] in names_AITs:
        os.rename(os.path.join(folder_to_process, file), os.path.join(AIT_folder_2018_2021, file))